### ISSUE TITLE
Form Components

### ISSUE THREAD

**Issue by slipperystairs** [romelperez/arwes#215]
Adding Arwes form components might be a neat feature.

**Comment by 1NF053C** [comment]
https://compassionandhardwork.com/mission.html

**Comment by romelperez** [comment]
Hey @slipperystairs !

I'm sorry for the delay.

The plan is that Arwes should provide low-to-medium level functionalities to create design systems, but Arwes itself will not be a design system. The Playground will contain more examples on how to create full-fledged UI components with the framework.

Thank you anyway for suggesting!
