### ISSUE TITLE
1.0.0-alpha.23 not work

### ISSUE THREAD

**Issue by emc2ws** [romelperez/arwes#216]
bug1:
![微信截图_20231205222219111](https://github.com/arwes/arwes/assets/4535890/24891717-e42e-4aa2-80a8-56b1c680c2bc)
![微信截图_202312052219411111](https://github.com/arwes/arwes/assets/4535890/9b113ddd-4a48-4909-b28b-edda6a1a45c9)
bug2:
![微信截图_202312052223171111](https://github.com/arwes/arwes/assets/4535890/788f1f53-6e27-4768-9305-dfa819d42097)
![微信截图_202312052225441](https://github.com/arwes/arwes/assets/4535890/0cbf8fb1-f36b-4b1d-8abc-b18b6a3cd664)
![微信截图_202312052226351](https://github.com/arwes/arwes/assets/4535890/0a1d4083-f5c9-4413-b47c-28b0c00ac388)
![微信截图_2023120522264511](https://github.com/arwes/arwes/assets/4535890/8c6c9fe3-393d-4b93-9ff8-a8dfaa398111)

env:
node 14.16.0
motion 10.16.4
react 18.2.0
@emotion/react 11.11.1

**Comment by romelperez** [comment]
Hey @emc2ws !

I'm sorry for the too long delay.

The first bug is because React doesn't support components `ref`s as string. You use to use the `useRef` hook.

The second one seems that the component doesn't have children so it doesn't have a size to render.
