### ISSUE TITLE
It's hard to use without documentation.

### ISSUE THREAD

**Issue by LeroyK111** [romelperez/arwes#217]
How do I use this library? Answer: By guessing and reasoning. 😂

**Comment by ThomasCode92** [comment]
This is an open-source project operates, and it's possible that the current maintainers may be facing time constraints. If you've discovered potential improvements or solutions, feel free to contribute by proposing updates to the documentation.

@romelperez, I'm curious about the future maintenance plans for this project. If there's an opportunity, I'd love to lend a hand. How can I assist in ensuring its continuity?

**Comment by shawngmc** [comment]
I'd also like to see more documentation, even if it's just more samples in the playground. For one thing, it's not really clear what ARWES entails and what's custom for the demo site.

For example, I'm trying to make a button (like the 'Develop' button on the docs). That seems like it would be a part of the toolkit, but it appears to actually be a part of the demo site app (https://github.com/arwes/arwes/blob/next/apps/docs/src/pages/docs.tsx#L6 pulls it from https://github.com/arwes/arwes/blob/next/apps/docs/src/ui/Button/Button.tsx).

Also willing to help, but I'm not well-versed in React.

**Comment by bangoo** [comment]
If there is any example how to use hexagon frames for the menu buttons? Can't find it on the playgroung.
