### ISSUE TITLE
css prop on SVG elements do not exist

### ISSUE THREAD

**Issue by 1NF053C** [romelperez/arwes#227]
## Describe the bug

Playground suggests the css property exists:
      <FrameSVGNefrex
        css={{
          '[data-name=bg]': {
            color: 'hsl(240, 75%, 10%)'
          },
          '[data-name=line]': {
            color: 'hsl(240, 75%, 50%)'
          }
        }}
      />

## To reproduce

Use the above example in Next.js, run a dev server with `npm run dev`

## Expected behavior

css property exists on that element

## Screenshots
```
Type '{ css: { '[data-name=bg]': { color: string; }; '[data-name=line]': { color: string; }; }; }' is not assignable to type 'IntrinsicAttributes & FrameSVGCornersProps'.
  Property 'css' does not exist on type 'IntrinsicAttributes & FrameSVGCornersProps'.ts(2322)
(property) css: {
    '[data-name=bg]': {
        color: string;
    };
    '[data-name=line]': {
        color: string;
    };
}
```
## Development environment

- Packages version: [e.g. 1.0.0-alpha.14]
- Node.js and NPM version: [e.g. Node.js 12.18, NPM 6.14]
- OS: [e.g. Ubuntu 20.04]

## Testing environment

- Browser: [e.g. Chrome 85.0]

**Comment by romelperez** [comment]
Hey @1NF053C !

`css` is a property from [Emotion](https://emotion.sh) dependency. In the sandbox it's like this:

```tsx
/** @jsx jsx */
import { jsx } from '@emotion/react';
import { FrameSVGNefrex } from '@arwes/react-frames';

const Sandbox = (): JSX.Element => {
  return (
    <FrameSVGNefrex
      css={{
        '[data-name=bg]': {
          color: 'hsl(180, 75%, 10%)'
        },
        '[data-name=line]': {
          color: 'hsl(180, 75%, 50%)'
        }
      }}
    />
  );
};
```

At the beginning there is the lines:

```tsx
/** @jsx jsx */
import { jsx } from '@emotion/react';
```

If you add them, you can use `css` prop to all React components which accept `className?: string`.

You can choose any other CSS styling strategy to style the frames elements if you want.

Let me know if you have any questions.

**Comment by 1NF053C** [comment]
When using Next.js, it might require adding additional config, but it's not too clear. I can get chatgpt to provide directions on adding a babel related plugin loader but I don't think Nextjs always uses babel (for example it might use SWC instead)

**Comment by 1NF053C** [comment]
Using
```
/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react';
```

Also does not work due to css prop not existing on the element props.

**Comment by romelperez** [comment]
If you want to use Emotion as a styling solution, you can set it up with their instructions:

https://emotion.sh/docs/typescript
https://emotion.sh/docs/css-prop

But it's not required for ARWES.

You can style the frame components using any other solution, simple CSS could be enough.
