### ISSUE TITLE
renderFrameSVGPaths does not exist in @arwes/react-frames';

### ISSUE THREAD

**Issue by 1NF053C** [romelperez/arwes#228]
## Describe the bug

Missing imports

import { renderFrameSVGPaths } from '@arwes/frames';
import { useFrameSVGRenderer } from '@arwes/react-frames';

## To reproduce

Try to import the above.

## Expected behavior

Expected imports to exist based on playground.

## Screenshots

```
Module '"@arwes/react-frames"' has no exported member 'useFrameSVGRenderer'.ts(2305)
import useFrameSVGRenderer
```

## Development environment

- Packages version: [e.g. 1.0.0-alpha.14]
- Node.js and NPM version: [e.g. Node.js 12.18, NPM 6.14]
- OS: [e.g. Ubuntu 20.04]

## Testing environment

- Browser: [e.g. Chrome 85.0]

**Comment by romelperez** [comment]
Hey @1NF053C ,

Please make sure all dependencies from ARWES installed in your project are version `1.0.0-alpha.23`. Also, please use only the `@arwes/react` package since it re-exports all the other packages data for simplicity.

**Comment by 1NF053C** [comment]
I'm using 1.0.0-alpha.23, and `renderFrameSVG` is exported but not `renderFrameSVGPaths`

**Comment by romelperez** [comment]
Try checking the actual version installed in your terminal:

```bash
cat ./node_modules/@arwes/react/package.json | grep version
```

If it's not the version, you need to fix it in your package manager.
