### ISSUE TITLE
Help Nextjs support @emotion/react

### ISSUE THREAD

**Issue by 1NF053C** [romelperez/arwes#229]
## Is your feature request related to a problem? Please describe

Next.js 14.2.5 has compatibility issues with @emotion/react: https://github.com/emotion-js/emotion/issues/2928#issuecomment-1888848189

## Describe the solution you'd like

It'd be nice to be able to use `arwes` animations without digging into compiler toolchain logic (without having to reconfigure nextjs, swc, babel, jsx pragmas, set up styling registries, etc)

## Describe alternatives you've considered

None come to mind, Nextjs team has open issue for @emotion/react support, however I'm not sure whether using another styling lib would be easier: https://github.com/emotion-js/emotion/issues/2928#issuecomment-1888848189

**Comment by romelperez** [comment]
ARWES doesn't work with React Server Components (RSC) and that's a limitation for all the tools which require stateful functionalities inside the components, Emotion one of them.

Gladly, the upcoming version of ARWES doesn't have a dependency with Emotion anymore but you still need to set up one styling solution in your project.
