### ISSUE TITLE
What could a map marker look like with Arwes design utils?

### ISSUE THREAD

**Issue by 1NF053C** [romelperez/arwes#231]
What are your thoughts? I dunno how to design something, but I can implement designs that I see. I can also brainstorm some thoughts[ex: micro-animation that is neon pulse that travels on roads but not over buildings would look neat] but I don't want to mess up someone else's creative process.

https://www.npmjs.com/package/@1nf053c/mapbox-map

https://dribbble.com/tags/map-marker

https://dribbble.com/search/fantasy-maps

**Comment by romelperez** [comment]
Hey @1NF053C ,

ARWES as a framework doesn't provide nor enforce any design system for you to design or implement. You can design whatever you see solves your needs and use ARWES as you see fit.

**Comment by 1NF053C** [comment]
It's a great framework, i could def use some help from a design community tho! :D
